
###
GET http://localhost:1234/products?type=salsa
Content-Type: application/json

###
GET http://localhost:1234/products?limit=1
Content-Type: application/json

###
GET http://localhost:1234/products/2
Content-Type: application/json

###
POST http://localhost:1234/products
Content-Type: application/json

{
  "nombre": "Esto es un producto de prueba" ,
  "type": ["Salsa picante"],
  "ingredientes": "no se no se no se nose",
  "picante": "nose ",
  "precio": 5,
  "imagen": "https://img.freepik.com/vector-gratis/lindo-icono-personajes-navidad-aislado_1308-121667.jpg",
  "moneda": "Usd"
}

###
PATCH http://localhost:1234/products/1
Content-Type: application/json

{
  "precio": 333,
  "moneda": "USD"
}

###
DELETE http://localhost:1234/products/7
Content-Type: application/json


